---
apiVersion: v2
name: s3gw
version: 0.7.0
kubeVersion: ">=1.14"
description: |
  Easy-to-use Open Source and Cloud Native S3 service for use on Rancher's Kubernetes.
type: application
keywords:
  - storage
  - s3
home: https://github.com/aquarist-labs/s3gw
icon: https://raw.githubusercontent.com/aquarist-labs/aquarium-website/gh-pages/images/logo-xl.png
sources:
  - https://github.com/aquarist-labs/s3gw-charts
  - https://github.com/aquarist-labs/s3gw
  - https://github.com/aquarist-labs/ceph
maintainers:
  - name: s3gw maintainers
    email: s3gw@suse.com
    url: https://github.com/orgs/aquarist-labs/projects/5
appVersion: "latest"
deprecated: false
annotations:
  app.aquarist-labs.io/name: s3gw
