---
apiVersion: v2
name: s3gw
version: 0.23.0
kubeVersion: ">=1.14"
description: |
  Easy-to-use Open Source and Cloud Native S3 service for use on Kubernetes.
type: application
keywords:
  - storage
  - s3
home: https://github.com/s3gw-tech/s3gw
icon: https://s3gw.tech/img/logo-xl.png
sources:
  - https://github.com/s3gw-tech/s3gw-charts
  - https://github.com/s3gw-tech/s3gw
  - https://github.com/s3gw-tech/s3gw-ceph
  - https://github.com/s3gw-tech/s3gw-ui
  - https://github.com/s3gw-tech/s3gw-cosi-driver
  - https://github.com/kubernetes-sigs/container-object-storage-interface-provisioner-sidecar
maintainers:
  - name: s3gw contributors
    email: contact@s3gw.tech
    url: https://github.com/orgs/s3gw-tech/projects/1
appVersion: "latest"
deprecated: false
annotations:
  artifacthub.io/category: storage
  artifacthub.io/links: |
    - name: homepage
      url: https://s3gw.tech/
    - name: support
      url: https://github.com/s3gw-tech/s3gw/issues
  app.s3gw.tech/name: s3gw
